initialize:
    rotateStepDegrees: 30
    visibilityDistance: 1.0
    gridSize: 0.25
    agentType: stochastic
    continuousMode: True
    snapToGrid: False
    agentMode: bot


width: 640
height: 480
max_steps: 500
